travis:
  secure:
    BINSTAR_TOKEN: Bt7HdaW7NOewEKSdBL7TYk0CkwT8p1EtJR3Snyw+nbMcpHsu8iNKqhw/JPx49KGPxA1GKgzH3MxZq3x5O2mkJM/tP4NqC1h45ygEJeZRCKU3K6AxKwv79dvaDFZqpDy7J7tVIhby6OE8Q5VgGvxiMNYZSOSwHdjbagXPYFiMbSZfZKdR0mZMjvWFAEqjegf3FNzVVPbR17DSq2cQxC+py+mNx/3FQfMYV/l0D/WHrN5pX2T4r+U63b7KmmqRZVSlMgymW/ieoJpqdHg3r0cXkB57frfRwUXCWdW/kNSH9TCQepCv20nQ/ef5C9QMIbgliQ3UucIr7Xk9YnnYl+TX9d0aoRQcxFDGFMlHSp3KLS5UY7VuNKn2C+LsioeCk2vzti/nu2I+t1SseAoz9a5k0eHjZsWpjBnXgcL5C3zbVEWGMAArY2uwQNkdFJioI5L5Q1dgdWUUE4sSYlkAPdXbG4v/t8qyjUf7zP4qyfoGGXx3v2o3+BsKBxB76S4rwuPDWMfGkKZ44Lg6GPH4J9ePY51zsPXwggJtjOLKJtbltGdFeWLDo3spQlGPBoUKy4yT9bqXkDz323QJErS0WYj24CwbQlwSwATmxMVJuKaGekb09qcOmH6Iybs0Uuyr7COmg2irN0aEnjMflcoDYjC+c91cijHriZxRhFPLjTh9Gu4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
